name: Notify New Discussion Comment to Slack

on:
  discussion_comment:
    types: [created]

jobs:
  discussion_commented:
    runs-on: ubuntu-latest

    steps:
      - name: Check discussion category
        run: |
          echo ${{ github.event.discussion.category.id }}
          echo ${{ github.event.discussion.category.node_id }}
          echo ${{ github.event.discussion.category.name }}
          echo ${{ github.event.discussion.category.slug }}
          echo ${{ github.event.discussion.category.description }}
