name: Notify New Discussion Comment to Slack

on:
  discussion_comment:
    types: [created]

jobs:
  discussion_commented:
    runs-on: ubuntu-latest

    env:
      CATEGORY_ID: DIC_kwDOJODuLs4Ces82

    steps:
      - name: Check discussion category
        run: |
          echo ${{ github.event.discussion.category.id }}
          echo ${{ github.event.discussion.category.node_id }}
          echo ${{ github.event.discussion.category.name }}
          echo ${{ github.event.discussion.category.slug }}
          echo ${{ github.event.discussion.category.description }}

      - name: Notify Discussion Comment for Frontend
        uses: slackapi/slack-github-action@v1.23.0
        if: github.event.discussion.category.node_id == env.CATEGORY_ID
        with:
          payload: |
            {
              "fallback": "New comment on <${{env.DISCUSSION_URL}}|${{env.DISCUSSION_TITLE}}>",
              "text": "New comment on <${{env.DISCUSSION_URL}}|${{env.DISCUSSION_TITLE}}>",
              "color": "#e85c28",
              "fields":[
                {
                  "title": "<${{env.COMMENT_URL}}|Comment>",
                  "value": "${{env.COMMENT_BODY}}",
                  "short": false
                }
              ]
            }
        env:
          DISCUSSION_TITLE: ${{ github.event.discussion.title }}
          DISCUSSION_URL: ${{ github.event.discussion.html_url }}
          COMMENT_URL: ${{ github.event.comment.html_url }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          USER_URL: ${{ github.event.comment.user.html_url }}
          USER_NAME: ${{ github.event.comment.user.login }}
          USER_AVATAR_URL: ${{ github.event.comment.user.avatar_url }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
