name: Notify New Discussion Comment to Slack

on:
  discussion_comment:
    types: [created]

jobs:
  discussion_commented:
    runs-on: ubuntu-latest

    env:
      CATEGORY_ID: DIC_kwDOJODuLs4Ces82

    steps:
      - name: Check discussion category
        run: |
          echo ${{ github.event.discussion.category.id }}
          echo ${{ github.event.discussion.category.node_id }}
          echo ${{ github.event.discussion.category.name }}
          echo ${{ github.event.discussion.category.slug }}
          echo ${{ github.event.discussion.category.description }}

      - name: Notify Discussion Comment for Frontend
        uses: slackapi/slack-github-action@v1.23.0
        if: github.event.discussion.category.node_id == env.CATEGORY_ID
        with:
          payload: |
            {
              "text": "New comment on <${{env.DISCUSSION_TITLE}}|${{env.DISCUSSION_URL}}>",
              "attachments":[
                "blocks":[
                  {
                    "type": "context",
                    "elements": [
                      {
                        "type": "mrkdwn",
                        "text": "${{env.COMMENT_BODY}}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "<${{env.COMMENT_URL}}|View Comment>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "by <${{env.USER_URL}}|${{env.USER_NAME}}>"
                      },
                      {
                        "type": "image",
                        "image_url": "${{env.USER_AVATAR_URL}}",
                        "alt_text": "${{env.USER_NAME}}"
                      }
                    ]
                  }
                ]
              ]
            }
        env:
          DISCUSSION_TITLE: ${{ github.event.discussion.title }}
          DISCUSSION_URL: ${{ github.event.discussion.html_url }}
          COMMENT_URL: ${{ github.event.comment.html_url }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          USER_URL: ${{ github.event.comment.user.html_url }}
          USER_NAME: ${{ github.event.comment.user.login }}
          USER_AVATAR_URL: ${{ github.event.comment.user.avatar_url }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
